title: Domainers Portfolio
email: info@domainersportfolio.com
description: "The #1 information source for professional domain‑name investors."
url: "https://domainersportfolio.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: default
search: true
timezone: America/Los_Angeles

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/

author:
  name: "Domainers Portfolio"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Actionable insights and data for domain‑name investors."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DomainersHQ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DomainersPortfolio"
    - label: "Discord"
      icon: "fas fa-fw fa-comments"
      url: "https://chat.domainersportfolio.com"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/DomainersHQ"
    - label: "Feed"
      icon: "fas fa-fw fa-rss"
      url: "/feed.xml"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DomainersPortfolio"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: single
      author_profile: true
